name: Clean Domain List

on:
  push:
    paths:
      - 'input.txt'
      - 'ambil_domain.py'
  workflow_dispatch:

jobs:
  clean-domains:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Run script to clean domain list
        run: |
          python ambil_domain.py input.txt output.txt

      - name: Commit and push output.txt
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add output.txt
          git commit -m "Update cleaned domain list"
          git push
